### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by jibanes** [computerpencils/ScraXBRL#2]
```
>>> from DataViewer import *
>>> a=DataView('A','2013-04-30','10-Q')
>>> a.traverse_tree('StatementOfFinancialPositionClassified')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "DataViewer.py", line 72, in traverse_tree
    base = self.data[cat]['roles'][name]
KeyError: 'StatementOfFinancialPositionClassified'
>>> a.data.keys()
['ins', 'cal', 'lab', 'pre', 'error', 'no_lineage']
>>> a.data['pre'].keys()
['xbrl_titles', 'roles']
>>> a.data['pre']['roles'].keys()
['AcquisitionOfDako', 'AcquisitionOfDakoDetailedTextualsDetails', 'AcquisitionOfDakoIntangiblesDetails', 'AcquisitionOfDakoProformaConsolidatedOperatingResultsDetails', 'AcquisitionOfDakoPurchasePriceAllocationDetails', 'AcquisitionOfDakoTables', 'CondensedConsolidatedBalanceSheetUnaudited', 'CondensedConsolidatedBalanceSheetUnauditedParenthetical', 'CondensedConsolidatedStatementOfCashFlowsUnaudited', 'CondensedConsolidatedStatementOfComprehensiveIncomeUnaudited', 'CondensedConsolidatedStatementOfComprehensiveIncomeUnauditedParenthetical', 'CondensedConsolidatedStatementOfOperationsUnaudited', 'Derivatives', 'DerivativesDetails', 'DerivativesDisclosuresAndDerivativeInstrumentAggregatedNotionalAmountsByCurrencyAndDesignationsDetails', 'DerivativesEffectOfDerivativeInstrumentsOnConsolidatedStatementOfOperationsDetails', 'DerivativesFairValueOfDerivativeInstrumentsAndConsolidatedBalanceSheetLocationDetails', 'DerivativesTables', 'DocumentAndEntityInformation', 'FairValueMeasurements', 'FairValueMeasurementsFairValueMeasuresAndImpairmentOfLongLivedAssetsDetails', 'FairValueMeasurementsFairValueOfAssetsAndLiabilitiesMeasuredOnRecurringBasisDetails', 'FairValueMeasurementsTables', 'GoodwillAndOtherIntangibleAssets', 'GoodwillAndOtherIntangibleAssetsDisclosuresAndComponentsOfPurchasedOtherIntangiblesDetails', 'GoodwillAndOtherIntangibleAssetsFiniteLivedAssetsFutureAmortizationExpenseDetails', 'GoodwillAndOtherIntangibleAssetsGoodwillAndOtherIntangibleAssetsTextualsDetails', 'GoodwillAndOtherIntangibleAssetsGoodwillRollForwardDetails', 'GoodwillAndOtherIntangibleAssetsTables', 'IncomeTaxes', 'IncomeTaxesDetails', 'Inventory', 'InventoryDetails', 'InventoryTables', 'LongTermDebt', 'LongTermDebtDetails', 'LongTermDebtLongTermDebtOtherDebtDetails', 'LongTermDebtTables', 'NetIncomePerShare', 'NetIncomePerShareDetails', 'NetIncomePerShareTables', 'NewAccountingPronouncements', 'OverviewBasisOfPresentationAndSummaryOfSignificantAccountingPolicies', 'OverviewBasisOfPresentationAndSummaryOfSignificantAccountingPoliciesDetails', 'OverviewBasisOfPresentationAndSummaryOfSignificantAccountingPoliciesPolicies', 'Restructuring', 'RestructuringDetails', 'RestructuringIncomeStatementLocationDetails', 'RestructuringTables', 'RetirementPlansAndPostRetirementPensionPlans', 'RetirementPlansAndPostRetirementPensionPlansDetails', 'RetirementPlansAndPostRetirementPensionPlansDetailsTextual', 'RetirementPlansAndPostRetirementPensionPlansTables', 'SegmentInformation', 'SegmentInformationProfitabilityAndSegmentAssetsDetails', 'SegmentInformationReconciliationOfReportableResultsDetails', 'SegmentInformationTables', 'ShareBasedCompensation', 'ShareBasedCompensationAllocatedShareBasedCompensationExpenseDetails', 'ShareBasedCompensationFairValueAssumptionsDetails', 'ShareBasedCompensationTables', 'ShortTermDebt', 'ShortTermDebtCreditFacilityDetails', 'ShortTermDebtSeniorNotesDetails', 'StockholdersEquity', 'StockholdersEquityStockRepurchaseProgramDetails', 'StockholdersEquityStockholdersEquityDividendsDetails', 'WarrantiesAndContingencies', 'WarrantiesAndContingenciesDetails', 'WarrantiesAndContingenciesTables']
>>> a.data['pre']['roles']['AcquisitionOfDako']
OrderedDict([('title_name', None), ('tree', OrderedDict([('BusinessCombinationsAbstract', OrderedDict([('pfx', 'us-gaap'), ('sub', OrderedDict([('BusinessCombinationDisclosureTextBlock', OrderedDict([('pfx', 'us-gaap'), ('sub', OrderedDict()), ('order', 1), ('val', OrderedDict()), ('label', 'Acquisition of Dako')]))])), ('label', u'Business Combinations [Abstract]')]))])), ('from_to', [('BusinessCombinationsAbstract', 'BusinessCombinationDisclosureTextBlock', '1', 'terseLabel')]), ('root', [('us-gaap', 'BusinessCombinationsAbstract', '1', 'terseLabel')]), ('unique', [('us-gaap', 'BusinessCombinationDisclosureTextBlock', '1', 'terseLabel'), ('us-gaap', 'BusinessCombinationsAbstract', '1', 'terseLabel')])])
>>> a.traverse_tree['AcquisitionOfDako']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'instancemethod' object has no attribute '__getitem__'

```

**Comment by jibanes** [comment]
closing bug, I understood my mistake.
